### ISSUE TITLE
Action Buttons

### ISSUE THREAD

**Issue by assafweinberg** [esthercrawford/EstherBot#14]
More of a question than an issue. When you create an action button like 

```
%[Button Text](postback:button action)
```

How do you specify the handler for the postback. What does "button action" map to? Can you show an example?

**Comment by Pol-Lanski** [comment]
Yeah, I'm having the same issue! I'd love it if someone could clarify.

**Comment by btutal** [comment]
i guess currently it looks for postbacks labels and uses them as a command.  %[Label](postback:anything) for this one it will answer like user says "Label" not sure but at least smooch supports said that.

**Comment by alavers** [comment]
Hey folks, I've updated the readme with some clarity around how postback buttons work:

https://github.com/esthercrawford/EstherBot/blob/master/README.md

**Comment by assafweinberg** [comment]
@alavers  - Thanks for the update. I still don't have it working though. It seems like the `app.post('/webhook', function(req, res, next) {` code fires only when the user types something, but not when they press an action button. It could be that I have something else wrong in my setup, but I'm not sure what.

Also, I'm surprised that the callback function that gets called depends on the user visible text, rather than the callback value. (e..g `%[user text](postback:postbackValue)` would trigger a state of "user text".

**Comment by kazekagekorosu** [comment]
there's also an issue with postback as well, the the text has to match the postback value...
so in your jscript file...it works like this...

The problem seems to be because of the way EstherBot was (oddly) coded. It's actually the button label that it sent as a reply. If you were to use this postback button:

 `%[Sure!](postback:multi_word)`
This would be fine usually; having multiple words isn't related to your issue and that would work under regular circumstances. When the user clicks on the postback, the bot is actually listening to Sure! instead. Which didn't have any entry in your script.json.

To fix your issue, you can add an entry for SURE!

`%[SURE!](postback:multi_word)`
`"SURE!":"...`
or rename the label to MULTI WORD.

```
%[MULTI WORD](postback:multi_word)
"MULTI WORD":"...
```

this is from Danny Tran from stackoverflow...so thanks to him for finding this! 

I think it's obvious but I'll state it again... 
you write 
`KEYWORD: "phrase here %[buttonlabel](postback:buttonlabel)",`
`BUTTONLABEL: "text from when buttons pushed",`
